#!/usr/bin/env bash
cd /home/bigdata/cwl/Gan/

#no random mask, no dropout
/home/bigdata/anaconda3/bin/python train.py --model_name=h_kolod_0_0 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_kolod.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_kolod.train --epoch=100 --batch_size=32 > ./run_logs/h_kolod_0_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_usoskin_0_0 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin.train --epoch=100 --batch_size=32 > ./run_logs/h_usoskin_0_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_pollen_0_0 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_pollen.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_pollen.train --epoch=100 --batch_size=32 > ./run_logs/h_pollen_0_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_usoskin_fgene_0_0 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin_fgene.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin_fgene.train --epoch=100 --batch_size=32 > ./run_logs/h_usoskin_fgene_0_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_brain_fgene_0_0 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain_fgene.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain_fgene.train --epoch=100 --batch_size=32 > ./run_logs/h_brain_fgene_0_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_brain_0_0 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain.train --epoch=100 --batch_size=32 > ./run_logs/h_brain_0_0.log 2>&1

#random_mask=0.9 no dropout
/home/bigdata/anaconda3/bin/python train.py --model_name=h_kolod_0.9_0 --truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_kolod.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_kolod.train --epoch=100 --batch_size=32 > ./run_logs/h_kolod_0.9_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_usoskin_0.9_0 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin.train --epoch=100 --batch_size=32 > ./run_logs/h_usoskin_0.9_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_pollen_0.9_0 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/h_pollen.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_pollen.train --epoch=100 --batch_size=32 > ./run_logs/h_pollen_0.9_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_usoskin_fgene_0.9_0 --truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin_fgene.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin_fgene.train --epoch=100 --batch_size=32 > ./run_logs/h_usoskin_fgene0.9_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_brain_fgene_0.9_0 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain_fgene.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain_fgene.train --epoch=100 --batch_size=32 > ./run_logs/h_brain_fgene_0.9_0.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_brain_0.9_0 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain.train --epoch=100 --batch_size=32 > ./run_logs/h_brain_0.9_0.log 2>&1

#no random mask, dropout=0.1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_kolod_0_0.1 --truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_kolod.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_kolod.train --epoch=100 --batch_size=32 > ./run_logs/h_kolod_0_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_usoskin_0_0.1 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin.train --epoch=100 --batch_size=32 > ./run_logs/h_usoskin_0_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_pollen_0_0.1 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_pollen.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/h_pollen.train --epoch=100 --batch_size=32 > ./run_logs/h_pollen_0_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_usoskin_fgene_0_0.1 --truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin_fgene.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin_fgene.train --epoch=100 --batch_size=32 > ./run_logs/h_usoskin_fgene_0_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_brain_fgene_0_0.1 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain_fgene.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain_fgene.train --epoch=100 --batch_size=32 > ./run_logs/h_brain_fgene_0_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_brain_0_0.1 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain.train --epoch=100 --batch_size=32 > ./run_logs/h_brain_0_0.1.log 2>&1

#random_mask=0.9, dropout=0.1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_kolod_0.9_0.1 --truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_kolod.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_kolod.train --epoch=100 --batch_size=32 > ./run_logs/h_kolod_0.9_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_usoskin_0.9_0.1 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin.train --epoch=100 --batch_size=32 > ./run_logs/h_usoskin_0.9_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_pollen_0.9_0.1 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_pollen.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_pollen.train --epoch=100 --batch_size=32 > ./run_logs/h_pollen_0.9_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_usoskin_fgene_0.9_0.1 --truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin_fgene.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_usoskin_fgene.train --epoch=100 --batch_size=32 > ./run_logs/h_usoskin_fgene_0.9_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_brain_fgene_0.9_0.1 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain_fgene.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain_fgene.train --epoch=100 --batch_size=32 > ./run_logs/h_brain_fgene_0.9_0.1.log 2>&1
/home/bigdata/anaconda3/bin/python train.py --model_name=h_brain_0.9_0.1 truly_mis_pro=0.9 --train_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain.train --infer_complete_datapath=/home/bigdata/cwl/Gan/data/cluster/h_brain.train --epoch=100 --batch_size=32 > ./run_logs/h_brain_0.9_0.1.log 2>&1